from django.urls import path

from .views import (
    Index,
    Index2,
    ListDeportista,
    DetailDeportista,
    CreateDeportista,
    UpdateDeportista,
    CreateDeporte,
    UpdateDeporte,
    ListDeporte,
    DetailDeporte,
    CreateInstitucion,
    UpdateInstitucion,
    ListInstitucion,
    CreateMedida,
    UpdateMedida,
    CreateCategoria,
    UpdateCategoria,
    ReporterView,
    ReporterTrainerView,
    ReporterDeportistaView,
)


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('2/', Index2.as_view(), name='index2'),
    path('deportista/list/', ListDeportista.as_view(), name='list-deportista'),
    path('deportista/detail/<int:pk>/', DetailDeportista.as_view(),
         name='detail-deportista'),
    path('deportista/add/', CreateDeportista.as_view(), name='add-deportista'),
    path('deportista/edit/<int:pk>/', UpdateDeportista.as_view(),
         name='edit-deportista'),
    path('deporte/add/', CreateDeporte.as_view(), name='add-deporte'),
    path('deporte/edit/<int:pk>', UpdateDeporte.as_view(), name='edit-deporte'),
    path('deporte/list/', ListDeporte.as_view(), name='list-deporte'),
    path('deporte/detail/<int:pk>/', DetailDeporte.as_view(),
         name='detail-deporte'),
    path('deporte/categoria/add/', CreateCategoria.as_view(),
         name='add-categoria'),
    path('deporte/categoria/edit/<int:pk>/', UpdateCategoria.as_view(),
         name='edit-categoria'),
    path('institucion/add/', CreateInstitucion.as_view(),
         name='add-institucion'),
    path('institucion/edit/<int:pk>/', UpdateInstitucion.as_view(),
         name='edit-institucion'),
    path('institucion/list/', ListInstitucion.as_view(),
         name='list-institucion'),
    path('medida/add/', CreateMedida.as_view(), name='add-medida'),
    path('medida/add/<int:deportista_pk>/', CreateMedida.as_view(),
         name='add-medida'),
    path('medida/edit/<int:pk>/', UpdateMedida.as_view(), name='edit-medida'),
    path('reportes/', ReporterView.as_view(), name='reporter'),
    path('reportes/entrenador/', ReporterTrainerView.as_view(),
         name='reporter-entrenador'),
    path('reportes/deportista/', ReporterDeportistaView.as_view(),
         name='reporter-deportista'),
]
