# Generated by Django 2.1.4 on 2019-01-31 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=45)),
                ('parametro_mayor_masa_grasa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('parametro_menor_masa_grasa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('parametro_mayor_masa_muscular', models.DecimalField(decimal_places=1, max_digits=3)),
                ('parametro_medio_masa_muscular', models.DecimalField(decimal_places=1, max_digits=3)),
                ('parametro_menor_masa_muscular', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=2)),
                ('foto', models.ImageField(default='/defautl/default_user.png', upload_to='deportista')),
                ('informacion_extra', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeportistaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=45, null=True)),
                ('contacto_emergencia_numero', models.CharField(blank=True, max_length=9, null=True)),
                ('eduacion', models.CharField(blank=True, max_length=120, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('deportista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.Deportista')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125, unique=True)),
                ('foto', models.ImageField(default='/defautl/default_institucion.png', upload_to='institucion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('peso_bruto', models.DecimalField(decimal_places=1, max_digits=4)),
                ('estatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('talla_sentado', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cintura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cadera', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humeral', models.DecimalField(decimal_places=1, max_digits=3)),
                ('femoral', models.DecimalField(decimal_places=1, max_digits=3)),
                ('brazo_flexionado', models.DecimalField(decimal_places=1, max_digits=3)),
                ('perimetro_pantorrilla', models.DecimalField(decimal_places=1, max_digits=3)),
                ('triceps', models.DecimalField(decimal_places=1, max_digits=3)),
                ('subescapular', models.DecimalField(decimal_places=1, max_digits=3)),
                ('biceps', models.DecimalField(decimal_places=1, max_digits=3)),
                ('suprailiaco', models.DecimalField(decimal_places=1, max_digits=3)),
                ('supraespinal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('abdominales', models.DecimalField(decimal_places=1, max_digits=3)),
                ('muslo_medio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pliege_pierna', models.DecimalField(decimal_places=1, max_digits=3)),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Deportista')),
            ],
        ),
        migrations.AddField(
            model_name='deportista',
            name='asociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.Institucion'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.Categoria'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.Deporte'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Deporte'),
        ),
    ]
