# Generated by Django 2.1.4 on 2019-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20190105_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=2),
            preserve_default=False,
        ),
    ]
