# Generated by Django 2.1.4 on 2019-01-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20190131_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportista',
            old_name='asociacion',
            new_name='institucion',
        ),
    ]
