# Generated by Django 2.1.4 on 2019-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20190131_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='foto',
            field=models.ImageField(default='defautl/default_user.png', upload_to='deportista'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(default='default/default_institucion.png', upload_to='institucion'),
        ),
    ]
