# Generated by Django 2.1.4 on 2019-01-06 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_deportista_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('peso_bruto', models.DecimalField(decimal_places=1, max_digits=4)),
                ('estatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('talla_sentado', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cintura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cadera', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humeral', models.DecimalField(decimal_places=1, max_digits=3)),
                ('femoral', models.DecimalField(decimal_places=1, max_digits=3)),
                ('brazo_flexionado', models.DecimalField(decimal_places=1, max_digits=3)),
                ('perimetro_pantorrilla', models.DecimalField(decimal_places=1, max_digits=3)),
                ('triceps', models.DecimalField(decimal_places=1, max_digits=3)),
                ('subescapular', models.DecimalField(decimal_places=1, max_digits=3)),
                ('biceps', models.DecimalField(decimal_places=1, max_digits=3)),
                ('suprailiaco', models.DecimalField(decimal_places=1, max_digits=3)),
                ('supraespinal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('abdominales', models.DecimalField(decimal_places=1, max_digits=3)),
                ('muslo_medio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pliege_pierna', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='deportista',
            name='foto',
            field=models.ImageField(default='/defautl/default_user.png', upload_to='deportista'),
        ),
        migrations.AddField(
            model_name='medida',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Deportista'),
        ),
    ]
