# Generated by Django 2.1.4 on 2019-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20190106_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociacion',
            name='foto',
            field=models.ImageField(default='/defautl/default_asociacion.png', upload_to='asociacion'),
        ),
    ]
